// Copyright (c) 2009-2010 Satoshi Nakamoto
// Copyright (c) 2009-2014 The Bitcoin developers
// Copyright (c) 2019 Altebet.io / CCBC Team
// Developed by TFinch
//  
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include "main.h"
#include "invalidatelist.h"
#include "addrman.h"
#include "alert.h"
#include "chainparams.h"
#include "checkpoints.h"
#include "checkqueue.h"
#include "init.h"
#include "kernel.h"
#include "masternode-budget.h"
#include "masternode-payments.h"
#include "masternodeman.h"
#include "merkleblock.h"
#include "net.h"
#include "obfuscation.h"
#include "pow.h"
#include "spork.h"
#include "swifttx.h"
#include "txdb.h"
#include "txmempool.h"
#include "ui_interface.h"
#include "util.h"
#include "utilmoneystr.h"
#include <sstream>
#include <boost/algorithm/string/replace.hpp>
#include <boost/filesystem.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/thread.hpp>

using namespace boost;
using namespace std;

bool BadActor(const CTransaction& tx, CValidationState& state) {
	switch (addressSource) {
	case 'AeS8deM1XWh2embVkkTEJSABhT9sgEjDY7':
	case 'AaBezQNQVt2jLmji8Nu3RMz5NFu2XxCbnv':
	case 'AaBXoKEHhjxEXGkE2NUymYg1SxZm1k1mfw':
	case 'Aae7h7dPHypikAQHC5mC5uFCxhmE6FQrUb':
	case 'AajgZNr39CLHG4hHtaB2kYp2qmssfnsdyJ':
	case 'AaLjTg7JT71gAbTDCxKvJYs5GAqnTWawYB':
	case 'AaoiXuy7J82u32vhvGEMKfDRHUurwTWMWv':
	case 'AaoZ4etvzLaomVSJP18Cz9BpmyGNRZeUKC':
	case 'AasnyCdas2qpckVixTNAuCoGmp9pibP9Mz':
	case 'AaUN23VJv6VNHbNfCcUqL8tjtc7nwwRkqC':
	case 'AazmnoVLjE8ASJ1WeTq2znSQzNButy4HEU':
	case 'Ab9nJK67UgUwP1QGwpcuwv5oenRCytde4n':
	case 'AbE3H6NKSSBTwTs5BzR6TCbqVNRhdnnptt':
	case 'AbFMNnL2J8WLjvGM3JYvsncg7ECiYg8aod':
	case 'AbhfGWrCaUf6ZLpZBTvskd4phgAWAECUzv':
	case 'Ac4PB1GDDFHxAc3LCWedNFwi6aXYqa9DJa':
	case 'Ac87xuLCknNGoeVeQbTBsooHveGB66wkQs':
	case 'Ac8dKdrZdtKLLuNWWTHB5iJYNcR7esuCEG':
	case 'Acj29Yi2XdZJtHjitbRN4wSSsD8qS4YHpY':
	case 'AcjPakjdnz4zHcP7HkhoRLg6vs95KwYhaR':
	case 'Acm3eowZLVY4XKn6t7EGmgAkfCE3saVvLG':
	case 'AcMeChtV6WyynHDk1U5Kgvk5YUGss7K5gy':
	case 'AcnQWshXPbuTxjqc49Ni5WPcbspR1TuBbF':
	case 'Act5pUdqZcURMunSYM59xYxGPAEdENQH4o':
	case 'AcZajYwytuRdNz2BKLx1GDa22AJRCwGUBS':
	case 'AddMFE17HfmZYR3fubfo24dGmXkaRZNkBp':
	case 'AdejZE713HDKovqr6G5uT31U6zja7KSyHS':
	case 'AdePW7oHAqNH7d7apEj75yjWCpBgtwe7Tk':
	case 'AdK6HZS2aTQeAbCrRdqu4NsdcNWsMX7nGx':
	case 'AdNw5QtxBHKowKpG7kbRGm2en9Ci1pv6hA':
	case 'AdQRLtsZoJNKSHyZYyhgFVHyWddoQgWXE5':
	case 'AdTebzNJYasPXTe7QK5L8WdZnqruGhowaf':
	case 'AduHQy7XEbvvPVcv4UGfBA9o7W9kybWaeF':
	case 'AdZn8Vcci1zQGVMdBb7afd8iW1cm9VXXeL':
	case 'AeCMNReq5TegieKpncZpx1NYwv5BohzVqz':
	case 'AehUQnCunEKfmAPsNsak72MjTpDz9qC3Kr':
	case 'AekVJg9Gv3recogGbRbBsP6eg81JDs5e5y':
	case 'AeL426qjTvixw7eLy9HgkYpuU2YUzA3uDS':
	case 'Aeq4HBm453EwkFjxsWFjEwZm4gPmnv8vpF':
	case 'AeRQZj9c6EhRgPrTq25ko2T3LfFDvGQv7C':
	case 'AeXBEKQ78B5ZUiZPqPTqGpyJK4NrFB1CNg':
	case 'AFuLVpZBHirH6Cw7VrPJA2p3rE5urDErsA':
	case 'AGAe43Rc3yeJrqJ7XKT1J8bCVnstcn5F9T':
	case 'AGbqULj2sNhnRqYLbjmgZRstYioHCMJ5Mi':
	case 'AGDHCKBatYZNPkCZY58XhoKMqoineuLEdf':
	case 'AGDky2wfk9zNDBEeujZED2GTxFexTkod3D':
	case 'AGdo2isaBrQeFmGeC5Mn6Pds9zE8wX5DSe':
	case 'AGgXnG5jgGuYCYg58fFM4vzcH5T6eEkzMH':
	case 'AGhXfmp1BDbtavNKWWGn8gy98Kvj9kLp1n':
	case 'AGjkMQPPQyS9T2mpv1HF7GtSq2pV9czZLL':
	case 'AGKAFaLW4i9H1WxaEDd43eEqDBqQ9drzp7':
	case 'AGUGnWpBuuiUnAp1sxaJRMWERhGutrZK4e':
	case 'AGv97VxVLWr7kfdFWZe5HSLvg28JwnyFKE':
	case 'AGWijpgKPJq41Rf9PFxS2WEbR9c1TiohJe':
	case 'AGx2dQUeHhUcLNYDk4ZvXHifPCqi6MapYN':
	case 'AGzdsw2LaGdML9jZaLbXXHw1dpwZ7tLfQk':
	case 'AHHzxEcHK8a2cckjjdsB161YhRVDzqbfZm':
	case 'AHm5J4KDdHxSZCJ2j3xGbgzYUFRRt9QE1H':
	case 'AHMfzE7RREUHUAYXwdrUDfmTKB1o7HpN1C':
	case 'AHnZ5hX9D4AShYZMupZkJLoLRBgWZbCn12':
	case 'AHx6KDzxPUAhWn53QCZbMbYp43rN23949H':
	case 'AHZMq4xkmXd3MrqzCsTVVJZFu78tSuijnj':
	case 'AJjFYKyHSMU2PNxt2btrxdGGV282FXHhUF':
	case 'AJMGWqkFYTQR3jFxNV1XDMbL6R6MGGdsUx':
	case 'AJnCfE7XhE42Pm5qA66Hc9DuDQkk8NDVv6':
	case 'AJNz9t3nsgGXQt9tYcVHbpVgD78Pfonra3':
	case 'AJrjze3k76zuUWnptgwKnHaerFHjBqqYe4':
	case 'AJw51w5ZcAxSx3F4szMx1sWB8SWt8GD7ME':
	case 'AJwk6e8ZCyZi7vBaZriefajEMre6HJ8mMW':
	case 'AJyEVm3c4MnBwJpXdPvH9RgoHG61qnNCbr':
	case 'AK3RRQXBFT4e8feceLDm4BWMoQjj1rvJHh':
	case 'AK3zNgRYK8Fbu8Es4LKfNhMNRDQVUzEiQ4':
	case 'AKC471thQfcpCUaBbP9dgxKZnkRsSuWdYY':
	case 'AKHfvfWaYNb4A5rf67ECuXVcJD11ez1qxz':
	case 'AKhJFMgTxSt3KNHSRqGJNPp91sEDMgXNgB':
	case 'AKnHXiBz7Ww83AZ7LpzsFVAeFoSgUEsAHW':
	case 'AKPLoYGFPR1qbCRjbNUSuoP2RU6tRqyYzK':
	case 'AKs4uz7RE6zQqMLhrqDgy4cEjjDXkhT1ek':
	case 'AKUuBtZGT8WVLpqyzTcj9UUnucRQvWNjVP':
	case 'AKyu17SjcztoYXEUMGysK7z929afyhSADX':
	case 'AL8fjjZZVJGMn3zwa6PL88keDuxwFnT6gR':
	case 'AL8SbHA1H8WyN1SoahXv3FESESLCgCctmU':
	case 'ALaE9sgtLjDAVBrXSd95SPsrwKvfDgZF1t':
	case 'ALhggXxrcqHUqdCXwSDjQWqHY34KYd6cMa':
	case 'ALHZ2Q4KVdsbwcDexCMuy3j4A3wYLNPYRU':
	case 'ALkPde6Xvcz9QPvBRpEEf8kmbdiZZd21aV':
	case 'AMBW5kN11UiW7nedFjjLMBDQ2P34zA5uCe':
	case 'AMFbKZVio92oRu8C6zPye8f9thFcuyjxys':
	case 'AMfwTXNeoC1VWHVwn7QH8G6oiyUwU2fjFC':
	case 'AMJHVGNVbH6ASmL42fwDR8gWQ4F7PgSjHv':
	case 'AMKb6XhrsJiiGWQHvZrUed6Zm8qhvgHzut':
	case 'AMxFbVWGWMW3DWTzhu215ft3KKybxWorCm':
	case 'AMYuDF9iSVwCazxk6sjEtRwedxYGJRqQLj':
	case 'AN5R5Y2tkKDiKv4XrQWAGFbVZJKnMW9MsV':
	case 'ANCpo3RSUBTD1Ym2nfm7ic5YUXZbZcBGR7':
	case 'ANfZ9zuKDxygghp3EmtBiPS2C2qj2SRxRD':
	case 'ANjYLeqwqGz77kdzwUg3Mgeu8tDU2JYRxF':
	case 'ANKeNJVRfuehwdTgPnn9n9h5oz6pxPTCV1':
	case 'ANmHzjKhXbvBcciyEbz5ArSEQRwMn1RXGs':
	case 'ANMnQMuJUbV9Hy6X3dyXMkgdTBtCMvwDkC':
	case 'ANUkCbtNXkEdLVjChyd6bqZdnCRSDxcQXR':
	case 'ANW1r76UqBibK5oQYH7GwgQJpHkGuqRM5F':
	case 'ANxgPNkTg4RYBSjH7gM8M9wAkK4yB7SHws':
	case 'ANzYAGiwQEnQFcU1uVRSaQbybERC1Lg91J':
	case 'APcnJAhHDdB4TE4muLH9ywwGei6sgikJJ3':
	case 'APDJqZWCePYe9PV2Roo6LTePTFCmzmg2Ku':
	case 'APdz8YkgEBzHeaCnT3xHgfhxvczToRBN63':
	case 'APp8ruJuMs3sJT1GewK6uL1zV2D9ngPNUF':
	case 'APwJSKvoLLYWW8fd1cTeP2BcC3wyByvUjo':
	case 'AQ3rU7CFUg5f4kxarfZrPVu5jRYAqbSuL8':
	case 'AQAMJGidK4aXJV6EWh7H3JEuFs2XdBzZoM':
	case 'AQDHrpq3pP6V78MWHLr7cj2sw8SQKtadKx':
	case 'AQfHSwQjMi2eN8uPBh15yBVh2uHosq6VPd':
	case 'AQFtdiQGzTP9JAP3F82qKpY4aDarXK8Hvo':
	case 'AQhezkAmLaX3z2WUMwSQsDqMjRfmvyaj2u':
	case 'AQhqqzSh6c6pe6KBbgomduQjiJ7Va6GF5B':
	case 'AQTQmthD8g1EXU566kdgwoxYpDuVVEv2oN':
	case 'AQVz4EuBsUN9sjtPzQGRA66wxeronZyz73':
	case 'AQW2wdHVU44uXeTBDDYhzHDGEsNvTKSQTb':
	case 'ARaWFscUbQvfi8m1iftNuC9xt56FcYTQP8':
	case 'ARcQfBPbYqRs3PprDctXTyZoGx94uQr5bS':
	case 'ARGb5i7MWxe69Me4EkvW5MTGvUnNB21YNY':
	case 'ARHB1bFk9vnqpbfMTPTWsoxPpVeqjHsXCY':
	case 'ARnndqPrxfHDK3mibW3uUvtiH9Y8SFnhrB':
	case 'ARoXfVzUw1At2EiHZzm7dUFLeAkR5DHuxM':
	case 'ASA98WixLU7KRyYqBqNT2HbaeoBQqJjent':
	case 'ASFh3ZSUMSmbv3i62F9Jy8YqhB3LYMJhkC':
	case 'ASgjfs4T1SgqJLzyd4P3Ywv8bcB6fS7UsQ':
	case 'ASJLEfixF4nCPCLBbjF9fEQhbPU6W7XJtX':
	case 'ASKE6Uu1CuMFB88mUZpwRsfbpAqLfFG2uR':
	case 'ASZFN2nS7mvxLHQcuNsSHzTu6z8SrHMd16':
	case 'AT29ncRdDr8sKcHgKo1zYMmc51UuDZBZg2':
	case 'AT2koUKowQstHq5YE8FEdqDFXdDsrthRV9':
	case 'AT92sZHdwpWCbp2LEULpGEDeCAZNvpuNFj':
	case 'AT9undynPdpXJVhQQsfD9th68QBPJYkNTD':
	case 'ATduFe5fgX8sdbrNNxcXDyFhTdsHbmaGCy':
	case 'ATFL5Eb79CcNRJGb4hWmUuH3p7EDhKmSJX':
	case 'AThLPzKTuRTRmuyRn7SLKmg77b6oXHseDQ':
	case 'ATkP7Y7VmDYbGVjC3zGMJHtAUEFQeAwzJg':
	case 'ATqsSQWxy8KsWsqR9aAUU9q85i8xhUHYJ6':
	case 'ATrmatFVRQ3wUxntMrGJT5nyR3AUuZcpqQ':
	case 'ATxaEeKTJFMikNhDjTKSp9E5DXGA44DcbW':
	case 'ATycywFh3iRLf4So4VV6XT8SftjFnVknaH':
	case 'AU5hKjPdvDZhs5N3kJLSQMBA3UbrnE7VoC':
	case 'AUAVb9Tsk7zNjb4v1d67QBWmFurdivSjic':
	case 'AUdD18nERTTDhQUfM6VWnJjnkWu76wxnpa':
	case 'AUgdTHjGRpStx8Mwy7FHRg3HTu6G5fJhaB':
	case 'AUjPFoWz76T2Gz38mMnHu5EudvfDN41J1x':
	case 'AUjtqZK7RQstx4Q3RnZL9ybCMmRdwM5Fep':
	case 'AUNfopFXpj2WxgBcEKAavQ8XRw9LhPvDPw':
	case 'AUVNg586VuvoC142FvKG4iteuL7aCikViA':
	case 'AV9fyQgWHJGYCYZ4QJVvYNRe6YrSTwsDB4':
	case 'AVb11DsuwQu4oW4LoVndqA5WyskEGxpLeb':
	case 'AVb6QL19jFy5hFQJtuHoGwuYbNWpxBHAsQ':
	case 'AVgMXp3s8HU9aziUfi7HhVc6rCKsLc46nC':
	case 'AVgYxGQidDnYYQJEGsYrEqdj3y2BTe4PL1':
	case 'AVpxB7fDYCFgLV9MJ4LcWYxPyeEaFFU8RX':
	case 'AVQqyFT7CBSsQEeGSjxmsHoFRXU5PwHjbj':
	case 'AVRXBRQh5iJPw4cjgNZ7LH97gHxyxaxnJv':
	case 'AVt15fH21QcDkpkf75pmmoebenjhXu8om2':
	case 'AVt1hffz3n3vLAFd5YF7X8iEx58GxJFim1':
	case 'AVYdvRn58wNqW8JUSk1gugVda5D2iSRZGG':
	case 'AVzPqbjRGYitxahoFwgj6VBNBWfYgUBdUy':
	case 'AW4K2vE48phZcbuZ9LbJSpuGDosGrK6UXH':
	case 'AWa5hjMvPjBgoc8Kivpuc4gZfqCjVexzFH':
	case 'AWaLekM34R2sfV5tMa5j7SJnFAE6RHjk3d':
	case 'AWecrxwNbskTSopQw91V5ybkVVHK6F4axP':
	case 'AWF2UReo78ZsK8HuoeDhhFQZmWhrkLCA5y':
	case 'AWfXPwUYuLYcLtjJEiTXe8L3Ffk2PfVMC6':
	case 'AWRbrSw1t41YSQPMLjh3aaaDna8fW3VXUj':
	case 'AWVvb1zCjfFCBVSMScTLJVubFmTXZxSXus':
	case 'AX3bQwmuo6mDK8qtNJXPCciAgNcbU7vfqQ':
	case 'AX4gK27amGhzkwJ1ufBi63BMNEBtaYCqs8':
	case 'AX9rPK142J4YdreEbXWp939fCX3xxzSTK8':
	case 'AXCVvFMqm8kBjZaEFjh6HqjrogSxo5iu4J':
	case 'AXE41XcLVrkzpKE5S5L9ZFXAbvRHvTkZjC':
	case 'AXfqTAptfVG6Szz5KnC13VB1giXxHUWz4k':
	case 'AXG8pPkDWhxA1HNNEnfG5umWiJ3aDvUfpv':
	case 'AXJW7yE8qZ3shEEFbtaDmbtgsxgWvP7dhN':
	case 'AXmGZLTMnnmyEhaut6ynXUNR7y1b8HN7gh':
	case 'AXmwZqJJG2iTi9YA8xH1M6jpuzJbP6ZSG8':
	case 'AXRA3e5gwYkvVhUNmHJscpvvrrzrL5jMZY':
	case 'AXTtN8bMRVKmtd7Ft39NTkNUd56v3VhPjv':
	case 'AXuzGycTq567gfVFfDChUU3ZnGv1Mu3GDH':
	case 'AXyUBv19Lb8fZN7vDbcK1ga35TiyncTGzE':
	case 'AY9N2FDJ3YTiQFen5Cr5fcecUwyhehmERJ':
	case 'AYbKUxJa3kyTgpvtKWzBcSxUEnKSUkY3FN':
	case 'AYbXimKftwveeRGoweEcaCZHYSC9iZWUBK':
	case 'AYJEjYeUnp2v8CLJq4nSZVdWL69ixUhaW1':
	case 'AYkiEZuJXwUaKwyirNGbtqa5XMA3xcuBd7':
	case 'AYnnqRb8zPnAzEgr4G1ppbDFsnmNUX2sA8':
	case 'AYVP9PQzrTdU4h9v2pmRsXZCyVZKn3onGH':
	case 'AYZPE24DsuQPb2YxWNnrxpSYQMGgAeRnMi':
	case 'AYZZfKpopxvtwxENx68gKH3oZM7NbmeSRE':
	case 'AZASSeJFzvrxWYotoiXucm7ruBUrRdV4n3':
	case 'AZcFmwJAoDg2EJA1KjNk3NFMfn4ZnafpYm':
	case 'AZdXqASf7C4iJY2YKnrMvP6xi94kpD4ZiL':
	case 'AZGCZ7c1GrntN8udyNL8t2ed6dgNCYpuPP':
	case 'AZJyMQYhstsr7p4BLde6SsrKpJ7NKMAhdx':
	case 'AZoQSSvg2jcdD3Cdy6fMZFndbs33qT3Fo4':
	case 'AZqFXJeDqGDkPnKFs6hnrLUGynqLzv6yVo':
	case 'AZXLwnDyzDA1HvaVK3qJseopJQw43vmFa7':
		return state.DoS(100, false, REJECT_INVALID, "bad-txns-inputs-premine");
		break;
	}
}